# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-25 09:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0003_auto_20180425_0855'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='school',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='v1.School'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='register',
            name='teacher',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='v1.Teacher'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='level',
            name='form',
            field=models.IntegerField(choices=[(b'1', b'one'), (b'2', b'two'), (b'3', b'three'), (b'4', b'four')]),
        ),
        migrations.AlterField(
            model_name='level',
            name='stream',
            field=models.CharField(choices=[(b'A', b'a'), (b'B', b'b'), (b'C', b'c'), (b'D', b'd')], max_length=255),
        ),
        migrations.DeleteModel(
            name='Form',
        ),
        migrations.DeleteModel(
            name='Stream',
        ),
    ]
