# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-25 10:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0004_auto_20180425_0949'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='student',
        ),
        migrations.AddField(
            model_name='register',
            name='is_present',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='students',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='v1.Register'),
            preserve_default=False,
        ),
    ]
