# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-25 10:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0005_auto_20180425_1043'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='students',
            new_name='register',
        ),
    ]
