# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-25 10:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0006_auto_20180425_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='register',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='v1.Register'),
        ),
    ]
